name: gss
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - antlr4-python3-runtime==4.9.3
  - graphviz
  - matplotlib
  - numpy
  - scipy
  - requests
  - pynput
  - screeninfo
  - pip:
    - antlr-denter
    - glog
    - lanelet2
    - py_trees==0.7.6
    - sysv-ipc
    - tk # Need to install from pip to support TrueType fonts
